## 3*4 array with random values

In [2]:
import numpy as np;
print("Array with random values\n",np.random.random((3,4)))

Array with random values
 [[0.57073158 0.16218982 0.82567856 0.49129275]
 [0.87264616 0.98713085 0.15265208 0.95795209]
 [0.40920745 0.77329218 0.16453162 0.03055041]]


### 3*4 array with zeros

In [3]:
import numpy as np;
print("Array with zeros\n",np.zeros((3,4)))

Array with zeros
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## One dimensional array with 5 to 30 step 2

In [6]:
import numpy as np;
print("One dimensional array\n",np.arange(5,31,2))

One dimensional array
 [ 5  7  9 11 13 15 17 19 21 23 25 27 29]


### Find shape,dimension,type of the array

In [10]:
import numpy as np;
a=np.array([[3,2,1],[5,8,9]])
print("Shap of the array is:",a.shape)
print("Dimension of the array is:",a.ndim)
print("Type of the array is:",a.dtype)

Shap of the array is: (2, 3)
Dimension of the array is: 2
Type of the array is: int64


### `Flatten the array

In [11]:
import numpy as np;
b=np.array([[4,7,8],[7,6,5]])
print("Flattened array is:",b.flatten())

Flattened array is: [4 7 8 7 6 5]
